CREATE TABLE [weibo] (
[id] TEXT  NOT NULL PRIMARY KEY,
[city_code] TEXT  NULL,
[_count] TEXT  NULL,
[country_code] TEXT  NULL,
[emotiontype] TEXT  NULL,
[emotionurl] TEXT  NULL,
[from] TEXT  NULL,
[fromurl] TEXT  NULL,
[geo] TEXT  NULL,
[head] TEXT  NULL,
[https_head] TEXT  NULL,
[image] TEXT  NULL,
[isrealname] TEXT  NULL,
[isvip] TEXT  NULL,
[jing] TEXT  NULL,
[latitude] TEXT  NULL,
[location] TEXT  NULL,
[longitude] TEXT  NULL,
[mcount] TEXT  NULL,
[music] TEXT  NULL,
[name] TEXT  NULL,
[nick] TEXT  NULL,
[openid] TEXT  NULL,
[origtext] TEXT  NULL,
[province_code] TEXT  NULL,
[self] TEXT  NULL,
[source] TEXT  NULL,
[status] TEXT  NULL,
[text] TEXT  NULL,
[timestamp] TEXT  NULL,
[type] TEXT  NULL,
[video] TEXT  NULL,
[wei] TEXT  NULL
);